In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
pd.__version__

'3.0.6'

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [5]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [6]:
len(df)

10000

In [7]:
df['fuel_type'].nunique()

3

In [8]:
len(df.columns[df.isna().any()])

2

In [9]:
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

np.float64(41.2)

In [10]:
df['horsepower'].median()

np.float64(254.0)

In [11]:
mostFreqHorsepower = df['horsepower'].value_counts().keys()[0]
print(mostFreqHorsepower)

252.0


In [12]:
df.fillna({'horsepower': mostFreqHorsepower}, inplace = True)
df['horsepower'].median()

np.float64(252.0)

In [13]:
X = df.loc[df['origin'] == 'Asia', ['vehicle_weight','model_year']].iloc[0:7].to_numpy()
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]


In [14]:
XT = X.T
print(XT)

[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]


In [15]:
XTX = XT @ X
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]


In [16]:
XTXinv = np.linalg.inv(XTX)
print(XTXinv)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]


In [17]:
y = np.asarray([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)

[1100 1300  800  900 1000 1100 1200]


In [18]:
w = XTXinv @ XT @ y
print(w)

[0.13644777 0.2327492 ]


In [19]:
np.sum(w)

np.float64(0.36919696904925486)